Repository dxw/playbook, pull requests merged in 2023-10, with the labels that each got.

#1190 Update Leave page “holiday”
  src/staff-handbook/leave/holiday.md
Labels: netlify-cms/draft

#1200 Update User Research page “choosing-and-using-analysis-and-synthesis-methods”
  src/user-research/choosing-and-using-analysis-and-synthesis-methods.md
Labels: netlify-cms/draft

#1201 Stronger guidance on using existing sources
  src/user-research/how-we-do-user-research.md
Labels: netlify-cms/pending_review

#1196 Update Technology page “support-and-on-call”
  src/tech/support-and-on-call.md
Labels: netlify-cms/pending_review

#1205 Update Technology page “web-accessibility”
  src/tech/web-accessibility.md
Labels: netlify-cms/pending_review

#1202 Stronger guidance on using existing sources
  src/user-research/choosing-and-using-analysis-and-synthesis-methods.md
Labels: netlify-cms/pending_review

#1203 Stronger guidance on using existing sources
  src/user-research/index.md
Labels: netlify-cms/pending_review

#1207 Value and act as well as understand people
  src/user-research/index.md
Labels: netlify-cms/pending_publish

#1208 Simplify descriptions of principles
  src/user-research/index.md
Labels: netlify-cms/pending_review

#1209 Simplify principle description
  src/user-research/index.md
Labels: netlify-cms/pending_review

#1216 Update Pay, pension and benefits page “benefits”
  src/staff-handbook/pay-pension-and-benefits/benefits.md
Labels: netlify-cms/draft
