Repository dxw/playbook, pull requests merged in 2023-07, with the labels that each got.

#1176 Update Staff handbook page “our-offices”
  src/staff-handbook/our-offices.md
Labels: netlify-cms/pending_publish

#1172 Update Leave page “TOIL”
  src/staff-handbook/leave/TOIL.md
Labels: netlify-cms/pending_review

#1168 Create Staff handbook page “leaving-dxw”
  src/staff-handbook/leaving-dxw.md
Labels: netlify-cms/draft

#1171 Update Pay, pension and benefits page “pension”
  src/staff-handbook/pay-pension-and-benefits/pension.md
Labels: netlify-cms/pending_review

#1179 Update Staff handbook page “covid-and-in-person-working”
  src/staff-handbook/covid-and-in-person-working.md
Labels: netlify-cms/draft

#1183 Update Delivery Management page “setting-up-a-new-project”
  src/delivery-management/setting-up-a-new-project.md
Labels: netlify-cms/pending_review
