Repository dxw/playbook, pull requests merged in 2025-05, with the labels that each got.

#1532 Create Parental leave page “neonatal-care-leave-and-pay”
  src/staff-handbook/policies-and-procedures/parental-leave.md
  src/staff-handbook/policies-and-procedures/parental-leave/neonatal-care-leave-and-pay.md
Labels: netlify-cms/pending_review

#1519 Update Staff handbook page “recording-your-time”
  src/staff-handbook/recording-your-time.md
Labels: netlify-cms/pending_review

#1556 Update Staff handbook page “data-protection-and-confidentiality”
  src/staff-handbook/data-protection-and-confidentiality.md
Labels: netlify-cms/pending_publish

#1557 Update About us page “how-to-raise-issues-and-share-feedback”
  src/about-us/how-to-raise-issues-and-share-feedback.md
Labels: netlify-cms/pending_publish

#1565 Create Parental leave page “unpaid-parental-leave”
  src/staff-handbook/policies-and-procedures/parental-leave/unpaid-parental-leave.md
Labels: netlify-cms/pending_review

#1564 Create Parental leave page “returning-to-work”
  src/staff-handbook/policies-and-procedures/parental-leave/returning-to-work.md
Labels: netlify-cms/pending_review

#1562 Create Parental leave page “shared-parental-leave”
  src/staff-handbook/policies-and-procedures/parental-leave/shared-parental-leave.md
Labels: netlify-cms/pending_review

#1559 Create Parental leave page “if-you’re-pregnant”
  src/staff-handbook/policies-and-procedures/parental-leave/if-you’re-pregnant.md
Labels: netlify-cms/draft
